# setting the `on join` page, you can select one of your inventory from inventory list below
joinpage: "welcome-1"

# loading type, you can use 
# "onjoin" to load the `join page` after player join the server
# "onresourcepack" to load the `join page` after player loaded the server's resourcepack
# "both" for both event.
loadtype: "onjoin"

# setting this to `true` will show the welcomeads to the player only once per server session.
persession: true

# the permission to give access to `welcomeads reload` command, normally give this to admin/owner role.
permission: "welcomeads.reload"

# this is the default background that will be used for all inventories if the background is not set.
# you can use the image from resourcepack, or use the hex color code.
global-background: 
  text: "&0%img_welcomeads_shift_l_1536%&e%img_welcomeads_background%&0%img_welcomeads_shift_l_1014%"
  fadein: 0
  stay: 0
  fadeout: 10