
# ------------------------------ WelcomeAds by TiNYsx ------------------------------
#
#                                   Plugin Section                                  
#
# ----------------------------------------------------------------------------------

# before start, this is just some information.
# this plugin use `tick` as a main time type, which can convert from 20 tick to 1 seconds.
# you can found materials name from here (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)
# you can found sounds name from here (https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html)

# setting the `on join` page, you can select one of your inventory from inventory list below
joinpage: "welcome1"

# loading type, you can use 
# "onstart" to load the `join page` after player join the server
# "onresourcepack" to load the `join page` after player loaded the server's resourcepack
# "both" for both event.
loadtype: "both"

# the permission to give access to `welcomeads reload` command, normally give this to admin/owner role.
permission: "welcomeads.reload"

# background setting
# set value to turn the background function on or off by using `true` or `false`
# set the background text. you can use PlaceholderAPI here, or if you got some font-image character, you can just use it here too.
# set the stay time of the title, this is using tick (20 tick = 1 seconds).
# set the fadeout time of the title, same as `stay`.
background: 
  enable: true
  text: "&0%img_welcomeads_shift_l_1536%&0%img_welcomeads_background%&0%img_welcomeads_shift_l_1014%"
  stay: 0
  fadeout: 10

# ----------------------------------------------------------------------------------
#
#                                  Screen Section                                   
#
# ----------------------------------------------------------------------------------

# inventory setting, here you can create as much inventory as you need, here you can
# set the inventory name, you can just use anything as it name
# turn on/off for this inventory; in case you just want to keep it there but don't want it to show in game. also remember, if the `enable` is `false` and there is a page pointing this page to be it's `nextpage`, the `nextpage` won't be appear.
# set the title of the inventory, you can use PlaceholderAPI or font-image here.
# set the open sound of the gui, such as chest open sound. but be careful, this might be annoying for player if you loop the page and every page has it own sound.
# set `nextpage` after this page. the paging system will automatically scroll to the nextpage after the `delay` time.
# set `delay` time to describe the delay that the page will change to the `nextpage` in tick.

# set `background` for a custom background, every component just as same as the global background.

# set `items` to setting up the item inside the inventory. here you can put it anywhere in the chest, which will start the index at 0 and end at 53. remember that this can't be use with player's inventory.
# for the `items` section, you will need
# `material` to describe the material of the item
# `slot` to set the slot index of item in the inventory, you can use 0 - 53
# `name` to set the item name
# `lore` to set the item lore, you can add more line using | - "lore" |, just add new line, that's it
# `modeldata` to set the item custom model data. please use only number(integer)

# `commands` to set the command list that will execute after clicked.
# for the `commands` section, you can use
# `[console]command` to run command by console
# `[player]command` to run command by player
# `[close]` to close the gui
# `[sound]` to to play the sound
# `<player>` to use it as a player name, ex "[console]help <player>" to show help command to the player who click the item

inventory:
  'welcome1':
    enable: true
    permission: "welcomeads.open.welcome1"
    title: "%img_welcomeads_page_1%"
    open-sound: "minecraft:ui.loom.select_pattern"
    nextpage: 'welcome2'
    delay: 100
    background: 
      enable: true
      text: "&0%img_welcomeads_shift_l_1536%&e%img_welcomeads_background%&0%img_welcomeads_shift_l_1014%"
      stay: 0
      fadeout: 10
    items:
      '1':
        material: "PLAYER_HEAD"
        slot: 48
        name: "&aPlayer Profile"
        lore:
        - "&r"
        - "&7Name: &a%player_name%"
        - "&fThanks for being part of our Community!"
        commands:
        - "[console]welcomeads open welcome2 <player>"
  'welcome2':
    enable: true
    permission: "welcomeads.open.welcome2"
    title: "%img_welcomeads_page_2%"
    open-sound: "minecraft:ui.loom.select_pattern"
    nextpage: 'welcome3'
    delay: 100
    items:
      '1':
        material: "EMERALD_BLOCK"
        modeldata: 0
        slot: 49
        name: "&fWelcome to the Server!"
        lore:
        - "&r"
        - "&aRules"
        - "&71.&fDo not use any cheat."
        - "&72.&fTreat every player with kindness."
        - "&r"
        - "&fEnjoy the server!"
        - "&r"
        commands:
        - "[console]welcomeads open welcome3 <player>"
  'welcome3':
    enable: true
    permission: "welcomeads.open.welcome3"
    title: "%img_welcomeads_page_3%"
    open-sound: "minecraft:ui.loom.select_pattern"
    nextpage: 'welcome1'
    delay: 100
    items:
      '1':
        material: "DIAMOND_BLOCK"
        modeldata: 0
        slot: 50
        name: "&fStore"
        lore:
        - "&r"
        - "&fBuy item in our Store!"
        - "&elink >> &7store.&courserver&7.com"
        - "&r"
        commands:
        - "[close]"