api: "1.21"
api-version: 1.21
name: WelcomeAds
version: "1.7"
main: com.tinysx.welcomeads.WelcomeAds
description: A normal ads welcome screen in minecraft with easy configuration. Supported by Erocavontic Creation
softdepend:
  - PlaceholderAPI
  - SkinsRestorer
commands:
  welcomeads:
    description: WelcomeAds command
    usage: /welcomeads <arg-1> <arg-2> <arg-3>